name: Build and publish development Docker images
on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches:
      - dev
    tags:
      - "v*"
  pull_request:

jobs:
  # https://github.com/marketplace/actions/build-and-push-docker-images
  multi-registries:
    # Note: Because latter steps depends on the `dev` version of an earlier step
    # , if you cancel the GitHub Action workflow for dev, it's possible that
    # the resulting images might not be built from the latest base image.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        # https://github.com/docker/setup-buildx-action#inputs
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the ylc_base image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./essential/base/Dockerfile
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ github.event_name != 'pull_request' }}
          tags: yenlincc/development-container-base,ghcr.io/yenlincc/development-container-base

      - name: Build and push ylc_rust
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./essential/rust/Dockerfile
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ github.event_name != 'pull_request' }}
          tags: yenlincc/development-container-rust,ghcr.io/yenlincc/development-container-rust

      - name: Build and push ylc_go
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./essential/go/Dockerfile
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ github.event_name != 'pull_request' }}
          tags: yenlincc/development-container-go,ghcr.io/yenlincc/development-container-go

      - name: Build and push ylc_cdk-go
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./projects/cdk-go/Dockerfile
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ github.event_name != 'pull_request' }}
          tags: yenlincc/development-container_cdk-go,ghcr.io/yenlincc/development-container_cdk-go

      - name: Build and push ylc_rust-lang_rust
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./projects/rust-lang/rust/Dockerfile
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ github.event_name != 'pull_request' }}
          tags: yenlincc/development-container_rust-lang_rust,ghcr.io/yenlincc/development-container_rust-lang_rust

      ## This is taking too long to build and is unused. Commented out for now.
      # - name: Docker meta for the ylc_bottlerocket-os_bottlerocket image
      #   id: docker_meta_ylc_bottlerocket-os_bottlerocket
      #   uses: crazy-max/ghaction-docker-meta@v1
      #   with:
      #     images: yenlincc/development-container_bottlerocket-os_bottlerocket,ghcr.io/yenlincc/development-container_bottlerocket-os_bottlerocket
      #     tag-sha: true
      # - name: Build and push ylc_bottlerocket-os_bottlerocket
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: ./projects/bottlerocket-os/bottlerocket/Dockerfile
      #     platforms: linux/amd64
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.docker_meta_ylc_bottlerocket-os_bottlerocket.outputs.tags }}
      #     labels: ${{ steps.docker_meta_ylc_bottlerocket-os_bottlerocket.outputs.labels }}
