name: Build and publish development Docker images
on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches:
      - dev
    tags:
      - "v*"
  pull_request:

jobs:
  # https://github.com/marketplace/actions/build-and-push-docker-images
  multi-registries:
    # Note: Because latter steps depends on the `dev` version of an earlier step
    # , if you cancel the GitHub Action workflow for dev, it's possible that
    # the resulting images might not be built from the latest base image.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        # https://github.com/docker/setup-buildx-action#inputs
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta for the ylc_base image
        id: docker_meta_ylc_base
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            yenlincc/development-container-base
            ghcr.io/yenlincc/development-container-base
          # https://github.com/docker/metadata-action#latest-tag
          tags: |
            type=semver,pattern={{raw}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'dev') }}
            type=raw,value=for-auto-build
            type=sha
      - name: Build and push the ylc_base image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./essential/base/Dockerfile
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_ylc_base.outputs.tags }}
          labels: ${{ steps.docker_meta_ylc_base.outputs.labels }}

      - name: Docker meta for the ylc_rust image
        id: docker_meta_ylc_rust
        uses: docker/metadata-action@v4
        with:
          images: |
            yenlincc/development-container-rust
            ghcr.io/yenlincc/development-container-rust
          # https://github.com/docker/metadata-action#latest-tag
          tags: |
            type=semver,pattern={{raw}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'dev') }}
            type=raw,value=for-auto-build
            type=sha
      - name: Build and push ylc_rust
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./essential/rust/Dockerfile
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_ylc_rust.outputs.tags }}
          labels: ${{ steps.docker_meta_ylc_rust.outputs.labels }}

      - name: Docker meta for the ylc_go image
        id: docker_meta_ylc_go
        uses: docker/metadata-action@v4
        with:
          images: |
            yenlincc/development-container-go
            ghcr.io/yenlincc/development-container-go
          tags: |
            type=semver,pattern={{raw}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'dev') }}
            type=raw,value=for-auto-build
            type=sha
      - name: Build and push ylc_go
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./essential/go/Dockerfile
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_ylc_go.outputs.tags }}
          labels: ${{ steps.docker_meta_ylc_go.outputs.labels }}

      - name: Docker meta for the ylc_cdk-go image
        id: docker_meta_ylc_cdk-go
        uses: docker/metadata-action@v4
        with:
          images: |
            yenlincc/development-container_cdk-go
            ghcr.io/yenlincc/development-container_cdk-go
          tags: |
            type=semver,pattern={{raw}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'dev') }}
            type=raw,value=for-auto-build
            type=sha
      - name: Build and push ylc_cdk-go
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./projects/cdk-go/Dockerfile
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_ylc_cdk-go.outputs.tags }}
          labels: ${{ steps.docker_meta_ylc_cdk-go.outputs.labels }}

      - name: Docker meta for the ylc_rust-lang_rust image
        id: docker_meta_ylc_rust-lang_rust
        uses: docker/metadata-action@v4
        with:
          images: |
            yenlincc/development-container_rust-lang_rust
            ghcr.io/yenlincc/development-container_rust-lang_rust
          tags: |
            type=semver,pattern={{raw}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'dev') }}
            type=raw,value=for-auto-build
            type=sha
      - name: Build and push ylc_rust-lang_rust
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./projects/rust-lang/rust/Dockerfile
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_ylc_rust-lang_rust.outputs.tags }}
          labels: ${{ steps.docker_meta_ylc_rust-lang_rust.outputs.labels }}